package com.cloud.baowang.play.game.acelt.enums;


import lombok.Getter;


/**
 * 彩种分类
 */
@Getter
public enum AceLtPlayTypeEnum {

    SMP_ZH_DXDSLHH("smp_zh_dxdslhh", "总和"),
    SMP_DXDSZH_D1Q("smp_dxdszh_d1q", "第一球"),
    SMP_SZ_D1Q("smp_sz_d1q", "第一球"),
    SMP_DXDSZH_D2Q("smp_dxdszh_d2q", "第二球"),
    SMP_SZ_D2Q("smp_sz_d2q", "第二球"),
    SMP_DXDSZH_D3Q("smp_dxdszh_d3q", "第三球"),
    SMP_SZ_D3Q("smp_sz_d3q", "第三球"),
    SMP_DXDSZH_D4Q("smp_dxdszh_d4q", "第四球"),
    SMP_SZ_D4Q("smp_sz_d4q", "第四球"),
    SMP_DXDSZH_D5Q("smp_dxdszh_d5q", "第五球"),
    SMP_SZ_D5Q("smp_sz_d5q", "第五球"),
    SMP_DXTB_SJ("smp_dxtb_sj", "三军总和大小"),
    SMP_DXTB_SJDX("smp_dxtb_sjdx", "三军总和大小"),
    SMP_DXTB_WS("smp_dxtb_ws", "围骰全骰"),
    SMP_DXTB_QS("smp_dxtb_qs", "围骰全骰"),
    SMP_DXTB_3_18DS("smp_dxtb_3_18ds", "点数"),
    SMP_DXTB_YXX("smp_dxtb_yxx", "鱼虾蟹"),
    SMP_GYJH_DXDS("smp_gyjh_dxds", "冠亚军和"),
    SMP_GYH3D19("smp_gyh3d19", "冠亚军和"),
    SMP_ZHGJ("smp_zhgj", "冠军"),
    SMP_D1D10GJ("smp_d1d10gj", "冠军"),
    SMP_ZHYJ("smp_zhyj", "亚军"),
    SMP_D1D10YJ("smp_d1d10yj", "亚军"),
    SMP_ZHD3M("smp_zhd3m", "第三名"),
    SMP_D1D10D3M("smp_d1d10d3m", "第三名"),
    SMP_ZHD4M("smp_zhd4m", "第四名"),
    SMP_D1D10D4M("smp_d1d10d4m", "第四名"),
    SMP_ZHD5M("smp_zhd5m", "第五名"),
    SMP_D1D10D5M("smp_d1d10d5m", "第五名"),
    SMP_ZHD6M("smp_zhd6m", "第六名"),
    SMP_D1D10D6M("smp_d1d10d6m", "第六名"),
    SMP_ZHD7M("smp_zhd7m", "第七名"),
    SMP_D1D10D7M("smp_d1d10d7m", "第七名"),
    SMP_ZHD8M("smp_zhd8m", "第八名"),
    SMP_D1D10D8M("smp_d1d10d8m", "第八名"),
    SMP_ZHD9M("smp_zhd9m", "第九名"),
    SMP_D1D10D9M("smp_d1d10d9m", "第九名"),
    SMP_ZHD10M("smp_zhd10m", "第十名"),
    SMP_D1D10D10M("smp_d1d10d10m", "第十名"),
    SMP_TMZH_DXDS("smp_tmzh_dxds", "特码整合"),
    SMP_TMZH_TMGG("smp_tmzh_tmgg", "特码过关"),
    SMP_TMZH_JDX("smp_tmzh_jdx", "极大小"),
    SMP_SWZH_SWXT("smp_swzh_swxt", "三位形态"),
    SMP_SWZH_DXDS_DYW("smp_swzh_dxds_dyw", "第一位"),
    SMP_XH_D1W("smp_xh_d1w", "第一位"),
    SMP_SWZH_DXDS_DEW("smp_swzh_dxds_dew", "第二位"),
    SMP_XH_D2W("smp_xh_d2w", "第二位"),
    SMP_SWZH_DXDS_DSW("smp_swzh_dxds_dsw", "第三位"),
    SMP_XH_D3W("smp_xh_d3w", "第三位"),
    SMP_ZH_HDXD_SLHWDWX("smp_zh_hdxdslhwdwx", "总和"),
    SMP_D1Q("smp_d1q", "第一球"),
    SMP_D2Q("smp_d2q", "第二球"),
    SMP_D3Q("smp_d3q", "第三球"),
    SMP_D4Q("smp_d4q", "第四球"),
    SMP_D5Q("smp_d5q", "第五球"),
    SMP_HQ_SM_DSD("smp_hq_sm_dsd", "红球"),
    SMP_HQ_SM_DXD("smp_hq_sm_dxd", "红球"),
    SMP_HQ_RX1("smp_hq_rx1", "红球"),
    SMP_LQ_SM("smp_lq_sm", "蓝球"),
    SMP_LQ_LQXH("smp_lq_lqxh", "蓝球"),
    SMP_BW_DXDSZH("smp_bw_dxdszh", "百位"),
    SMP_YZDWBW("smp_yzdwbw", "百位"),
    SMP_SW_DXDSZH("smp_sw_dxdszh", "十位"),
    SMP_YZDWSW("smp_yzdwsw", "十位"),
    SMP_GW_DXDSZH("smp_gw_dxdszh", "个位"),
    SMP_YZDWGW("smp_yzdwgw", "个位"),
    SMP_BS_HDSWDXZH("smp_bs_hdswdxzh", "百十位"),
    SMP_BG_HDSWDXZH("smp_bg_hdswdxzh", "百个位"),
    SMP_SG_HDSWDXZH("smp_sg_hdswdxzh", "十个位"),
    SMP_BSG_HDSWDXZH("smp_bsg_hdswdxzh", "百十个位"),
    SMP_TM_DXDS("smp_tm_dxds", "特码双面"),
    SMP_TM_HDX("smp_tm_hdx", "特码双面"),
    SMP_TM_HDS("smp_tm_hds", "特码双面"),
    SMP_TM_TDX("smp_tm_tdx", "特码双面"),
    SMP_TM_QHX("smp_tm_qhx", "特码双面"),
    SMP_TM_JYX("smp_tm_jyx", "特码双面"),
    SMP_TM_WDX("smp_tm_wdx", "特码双面"),
    SMP_TM_DDXDDSXS("smp_tm_ddxddsxs", "特码双面"),
    SMP_TM_HM("smp_tm_hm", "特码选号"),
    SMP_TM_HLLB("smp_tm_hllb", "特码色波"),
    SMP_TM_BB("smp_tm_bb", "特码半波"),
    SMP_TM_BBB("smp_tm_bbb", "特码半半波"),
    SMP_TM_TX("smp_tm_tx", "特码特肖"),
    SMP_TM_TS("smp_tm_ts", "特码头数"),
    SMP_TM_WS("smp_tm_ws", "特码尾数"),
    SMP_TM_WX("smp_tm_wx", "特码五行"),
    SMP_ZM_RX1("smp_zm_rx1", "正码任选一"),
    SMP_ZM_Z1M_DXDSHDHSHDHXWDWXHLLB("smp_zm_z1m_dxdshdhshdhxwdwxhllb", "正码一"),
    SMP_ZM_Z2M_DXDSHDHSHDHXWDWXHLLB("smp_zm_z2m_dxdshdhshdhxwdwxhllb", "正码二"),
    SMP_ZM_Z3M_DXDSHDHSHDHXWDWXHLLB("smp_zm_z3m_dxdshdhshdhxwdwxhllb", "正码三"),
    SMP_ZM_Z4M_DXDSHDHSHDHXWDWXHLLB("smp_zm_z4m_dxdshdhshdhxwdwxhllb", "正码四"),
    SMP_ZM_Z5M_DXDSHDHSHDHXWDWXHLLB("smp_zm_z5m_dxdshdhshdhxwdwxhllb", "正码五"),
    SMP_ZM_Z6M_DXDSHDHSHDHXWDWXHLLB("smp_zm_z6m_dxdshdhshdhxwdwxhllb", "正码六"),
    SMP_ZM_ZX("smp_zm_zx", "正码正肖"),
    SMP_ZM_QSB("smp_zm_qsb", "正码七色波"),
    SMP_ZH("smp_zh", "总和"),
    SMP_VNNSM_QJ_DSDH("smp_vnnsm_qj_dsdh", "全奖"),
    SMP_VNNSM_QJ_DXDH("smp_vnnsm_qj_dxdh", "全奖"),
    SMP_VNNSM_QJ_NWDH("smp_vnnsm_qj_nwdh", "全奖"),
    SMP_VNNSM_TJ_ZH("smp_vnnsm_tj_zh", "特奖总和"),
    SMP_VNNSM_TJ_QE("smp_vnnsm_tj_qe", "特奖前二"),
    SMP_VNNSM_TJ_HE("smp_vnnsm_tj_he", "特奖后二"),
    SMP_VNNSM_TJ_WW("smp_vnnsm_tj_ww", "特奖万位"),
    SMP_VNNDWD_TJ_WW("smp_vnndwd_tj_ww", "特奖万位"),
    SMP_VNNSM_TJ_QW("smp_vnnsm_tj_qw", "特奖千位"),
    SMP_VNNDWD_TJ_QW("smp_vnndwd_tj_qw", "特奖千位"),
    SMP_VNNSM_TJ_BW("smp_vnnsm_tj_bw", "特奖百位"),
    SMP_VNNDWD_TJ_BW("smp_vnndwd_tj_bw", "特奖百位"),
    SMP_VNNSM_TJ_SW("smp_vnnsm_tj_sw", "特奖十位"),
    SMP_VNNDWD_TJ_SW("smp_vnndwd_tj_sw", "特奖十位"),
    SMP_VNNSM_TJ_GW("smp_vnnsm_tj_gw", "特奖个位"),
    SMP_VNNDWD_TJ_GW("smp_vnndwd_tj_gw", "特奖个位"),
    SMP_VNNSM_YJ_ZH("smp_vnnsm_yj_zh", "一奖总和"),
    SMP_VNNSM_YJ_QE("smp_vnnsm_yj_qe", "一奖前二"),
    SMP_VNNSM_YJ_HE("smp_vnnsm_yj_he", "一奖后二"),
    SMP_VNNSM_YJ_WW("smp_vnnsm_yj_ww", "一奖万位"),
    SMP_VNNDWD_YJ_WW("smp_vnndwd_yj_ww", "一奖万位"),
    SMP_VNNSM_YJ_QW("smp_vnnsm_yj_qw", "一奖千位"),
    SMP_VNNDWD_YJ_QW("smp_vnndwd_yj_qw", "一奖千位"),
    SMP_VNNSM_YJ_BW("smp_vnnsm_yj_bw", "一奖百位"),
    SMP_VNNDWD_YJ_BW("smp_vnndwd_yj_bw", "一奖百位"),
    SMP_VNNSM_YJ_SW("smp_vnnsm_yj_sw", "一奖十位"),
    SMP_VNNDWD_YJ_SW("smp_vnndwd_yj_sw", "一奖十位"),
    SMP_VNNSM_YJ_GW("smp_vnnsm_yj_gw", "一奖个位"),
    SMP_VNNDWD_YJ_GW("smp_vnndwd_yj_gw", "一奖个位"),
    SMP_VNCSM_QJ_DSDH("smp_vncsm_qj_dsdh", "全奖"),
    SMP_VNCSM_QJ_DXDH("smp_vncsm_qj_dxdh", "全奖"),
    SMP_VNCSM_QJ_NWDH("smp_vncsm_qj_nwdh", "全奖"),
    SMP_VNCSM_TJ_ZH("smp_vncsm_tj_zh", "特奖总和"),
    SMP_VNCSM_TJ_QE("smp_vncsm_tj_qe", "特奖前二"),
    SMP_VNCSM_TJ_HE("smp_vncsm_tj_he", "特奖后二"),
    SMP_VNCSM_TJ_SWW("smp_vncsm_tj_sww", "特奖十万位"),
    SMP_VNCDWD_TJ_SWW("smp_vncdwd_tj_sww", "特奖十万位"),
    SMP_VNCSM_TJ_WW("smp_vncsm_tj_ww", "特奖万位"),
    SMP_VNCDWD_TJ_WW("smp_vncdwd_tj_ww", "特奖万位"),
    SMP_VNCSM_TJ_QW("smp_vncsm_tj_qw", "特奖千位"),
    SMP_VNCDWD_TJ_QW("smp_vncdwd_tj_qw", "特奖千位"),
    SMP_VNCSM_TJ_BW("smp_vncsm_tj_bw", "特奖百位"),
    SMP_VNCDWD_TJ_BW("smp_vncdwd_tj_bw", "特奖百位"),
    SMP_VNCSM_TJ_SW("smp_vncsm_tj_sw", "特奖十位"),
    SMP_VNCDWD_TJ_SW("smp_vncdwd_tj_sw", "特奖十位"),
    SMP_VNCSM_TJ_GW("smp_vncsm_tj_gw", "特奖个位"),
    SMP_VNCDWD_TJ_GW("smp_vncdwd_tj_gw", "特奖个位"),
    SMP_VNCSM_YJ_ZH("smp_vncsm_yj_zh", "一奖总和"),
    SMP_VNCSM_YJ_QE("smp_vncsm_yj_qe", "一奖前二"),
    SMP_VNCSM_YJ_HE("smp_vncsm_yj_he", "一奖后二"),
    SMP_VNCSM_YJ_WW("smp_vncsm_yj_ww", "一奖万位"),
    SMP_VNCDWD_YJ_WW("smp_vncdwd_yj_ww", "一奖万位"),
    SMP_VNCSM_YJ_QW("smp_vncsm_yj_qw", "一奖千位"),
    SMP_VNCDWD_YJ_QW("smp_vncdwd_yj_qw", "一奖千位"),
    SMP_VNCSM_YJ_BW("smp_vncsm_yj_bw", "一奖百位"),
    SMP_VNCDWD_YJ_BW("smp_vncdwd_yj_bw", "一奖百位"),
    SMP_VNCSM_YJ_SW("smp_vncsm_yj_sw", "一奖十位"),
    SMP_VNCDWD_YJ_SW("smp_vncdwd_yj_sw", "一奖十位"),
    SMP_VNCSM_YJ_GW("smp_vncsm_yj_gw", "一奖个位"),
    SMP_VNCDWD_YJ_GW("smp_vncdwd_yj_gw", "一奖个位"),
    SMP_VNSSM_QJ_DSDH("smp_vnssm_qj_dsdh", "全奖"),
    SMP_VNSSM_QJ_DXDH("smp_vnssm_qj_dxdh", "全奖"),
    SMP_VNSSM_QJ_NWDH("smp_vnssm_qj_nwdh", "全奖"),
    SMP_VNSSM_TJ_ZH("smp_vnssm_tj_zh", "特奖总和"),
    SMP_VNSSM_TJ_QE("smp_vnssm_tj_qe", "特奖前二"),
    SMP_VNSSM_TJ_HE("smp_vnssm_tj_he", "特奖后二"),
    SMP_VNSSM_TJ_SWW("smp_vnssm_tj_sww", "特奖十万位"),
    SMP_VNSDWD_TJ_SWW("smp_vnsdwd_tj_sww", "特奖十万位"),
    SMP_VNSSM_TJ_WW("smp_vnssm_tj_ww", "特奖万位"),
    SMP_VNSDWD_TJ_WW("smp_vnsdwd_tj_ww", "特奖万位"),
    SMP_VNSSM_TJ_QW("smp_vnssm_tj_qw", "特奖千位"),
    SMP_VNSDWD_TJ_QW("smp_vnsdwd_tj_qw", "特奖千位"),
    SMP_VNSSM_TJ_BW("smp_vnssm_tj_bw", "特奖百位"),
    SMP_VNSDWD_TJ_BW("smp_vnsdwd_tj_bw", "特奖百位"),
    SMP_VNSSM_TJ_SW("smp_vnssm_tj_sw", "特奖十位"),
    SMP_VNSDWD_TJ_SW("smp_vnsdwd_tj_sw", "特奖十位"),
    SMP_VNSSM_TJ_GW("smp_vnssm_tj_gw", "特奖个位"),
    SMP_VNSDWD_TJ_GW("smp_vnsdwd_tj_gw", "特奖个位"),
    SMP_VNSSM_YJ_ZH("smp_vnssm_yj_zh", "一奖总和"),
    SMP_VNSSM_YJ_QE("smp_vnssm_yj_qe", "一奖前二"),
    SMP_VNSSM_YJ_HE("smp_vnssm_yj_he", "一奖后二"),
    SMP_VNSSM_YJ_WW("smp_vnssm_yj_ww", "一奖万位"),
    SMP_VNSDWD_YJ_WW("smp_vnsdwd_yj_ww", "一奖万位"),
    SMP_VNSSM_YJ_QW("smp_vnssm_yj_qw", "一奖千位"),
    SMP_VNSDWD_YJ_QW("smp_vnsdwd_yj_qw", "一奖千位"),
    SMP_VNSSM_YJ_BW("smp_vnssm_yj_bw", "一奖百位"),
    SMP_VNSDWD_YJ_BW("smp_vnsdwd_yj_bw", "一奖百位"),
    SMP_VNSSM_YJ_SW("smp_vnssm_yj_sw", "一奖十位"),
    SMP_VNSDWD_YJ_SW("smp_vnsdwd_yj_sw", "一奖十位"),
    SMP_VNSSM_YJ_GW("smp_vnssm_yj_gw", "一奖个位"),
    SMP_VNSDWD_YJ_GW("smp_vnsdwd_yj_gw", "一奖个位"),
    SMP_W4D_SM_QJ("smp_w4d_sm_qj", "全奖"),
    SMP_W4D_SM_1J_QW("smp_w4d_sm_1j_qw", "首奖千位"),
    SMP_W4D_XH_1J_QW("smp_w4d_xh_1j_qw", "首奖千位"),
    SMP_W4D_SM_1J_BW("smp_w4d_sm_1j_bw", "首奖百位"),
    SMP_W4D_XH_1J_BW("smp_w4d_xh_1j_bw", "首奖百位"),
    SMP_W4D_SM_1J_SW("smp_w4d_sm_1j_sw", "首奖十位"),
    SMP_W4D_XH_1J_SW("smp_w4d_xh_1j_sw", "首奖十位"),
    SMP_W4D_SM_1J_GW("smp_w4d_sm_1j_gw", "首奖个位"),
    SMP_W4D_XH_1J_GW("smp_w4d_xh_1j_gw", "首奖个位"),
    SMP_W4D_SM_2J_QW("smp_w4d_sm_2j_qw", "二奖千位"),
    SMP_W4D_XH_2J_QW("smp_w4d_xh_2j_qw", "二奖千位"),
    SMP_W4D_SM_2J_BW("smp_w4d_sm_2j_bw", "二奖百位"),
    SMP_W4D_XH_2J_BW("smp_w4d_xh_2j_bw", "二奖百位"),
    SMP_W4D_SM_2J_SW("smp_w4d_sm_2j_sw", "二奖十位"),
    SMP_W4D_XH_2J_SW("smp_w4d_xh_2j_sw", "二奖十位"),
    SMP_W4D_SM_2J_GW("smp_w4d_sm_2j_gw", "二奖个位"),
    SMP_W4D_XH_2J_GW("smp_w4d_xh_2j_gw", "二奖个位"),
    SMP_W4D_SM_3J_QW("smp_w4d_sm_3j_qw", "三奖千位"),
    SMP_W4D_XH_3J_QW("smp_w4d_xh_3j_qw", "三奖千位"),
    SMP_W4D_SM_3J_BW("smp_w4d_sm_3j_bw", "三奖百位"),
    SMP_W4D_XH_3J_BW("smp_w4d_xh_3j_bw", "三奖百位"),
    SMP_W4D_SM_3J_SW("smp_w4d_sm_3j_sw", "三奖十位"),
    SMP_W4D_XH_3J_SW("smp_w4d_xh_3j_sw", "三奖十位"),
    SMP_W4D_SM_3J_GW("smp_w4d_sm_3j_gw", "三奖个位"),
    SMP_W4D_XH_3J_GW("smp_w4d_xh_3j_gw", "三奖个位");
    // 成员变量
    private final String code;  // 彩种代码
    private final String name;  // 彩种名称

    public static String getNameByCode(String code){
        if(code == null){
            return null;
        }
        for (AceLtPlayTypeEnum num : AceLtPlayTypeEnum.values()){
            if(num.getCode().equals(code)){
                return num.getName();
            }
        }
        return null;
    }

    // 构造方法
    AceLtPlayTypeEnum(String code, String name) {
        this.code = code;
        this.name = name;
    }
}
