INSERT INTO `system_param` (`id`, `type`, `code`, `value`, `value_desc`, `description`, `created_time`, `updated_time`,
                            `creator`, `updater`)
VALUES (1123123342623460, 'activity_template', 'CHECKIN', 'LOOKUP_11108', '签到', '活动类型模板', 1, NULL, '1', NULL);

INSERT INTO `system_param` (`id`, `type`, `code`, `value`, `value_desc`, `description`, `created_time`, `updated_time`,
                            `creator`, `updater`)
VALUES (1123123342623463, 'activity_prize_source_show', '4', 'LOOKUP_11055', '签到活动', '转盘活动奖励来源', 1, NULL,
        '1', NULL);



INSERT INTO `system_param` (`type`, `code`, `value`, `value_desc`, `description`, `created_time`, `updated_time`,
                            `creator`, `updater`)
VALUES ('activity_daily_ranking', '11', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', '第十一名', '第十一名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '12', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', '第十二名', '第十二名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '13', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', '第十三名', '第十三名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '14', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', '第十四名', '第十四名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '15', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', '第十五名', '第十五名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '16', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', '第十六名', '第十六名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '17', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', '第十七名', '第十七名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '18', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', '第十八名', '第十八名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '19', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', '第十九名', '第十九名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '20', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', '第二十名', '第二十名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '21', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', '第二十一名', '第二十一名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '22', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', '第二十二名', '第二十二名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '23', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', '第二十三名', '第二十三名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '24', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', '第二十四名', '第二十四名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '25', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', '第二十五名', '第二十五名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '26', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', '第二十六名', '第二十六名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '27', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', '第二十七名', '第二十七名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '28', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', '第二十八名', '第二十八名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '29', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', '第二十九名', '第二十九名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '30', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', '第三十名', '第三十名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '31', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', '第三十一名', '第三十一名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '32', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', '第三十二名', '第三十二名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '33', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', '第三十三名', '第三十三名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '34', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', '第三十四名', '第三十四名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '35', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', '第三十五名', '第三十五名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '36', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', '第三十六名', '第三十六名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '37', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', '第三十七名', '第三十七名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '38', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', '第三十八名', '第三十八名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '39', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', '第三十九名', '第三十九名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '40', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', '第四十名', '第四十名', 1, NULL, '1', NULL),
       ('activity_daily_ranking', '41', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', '第四十一名', '第四十一名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '42', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', '第四十二名', '第四十二名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '43', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', '第四十三名', '第四十三名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '44', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', '第四十四名', '第四十四名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '45', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', '第四十五名', '第四十五名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '46', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', '第四十六名', '第四十六名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '47', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', '第四十七名', '第四十七名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '48', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', '第四十八名', '第四十八名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '49', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', '第四十九名', '第四十九名', 1, NULL, '1',
        NULL),
       ('activity_daily_ranking', '50', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', '第五十名', '第五十名', 1, NULL, '1', NULL);



INSERT INTO `i18n_message` (`message_type`, `message_key`, `language`, `message`, created_time)
VALUES ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', 'en-US', 'Rank Eleven', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', 'zh-TW', '第11名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', 'pt-BR', 'décimo primeiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', 'zh-CN', '第11名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', 'vi-VN', 'Hạng 11', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_11', 'ko-KR', '11위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', 'en-US', 'Rank Twelve', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', 'zh-TW', '第12名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', 'pt-BR', 'décimo segundo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', 'zh-CN', '第12名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', 'vi-VN', 'Hạng 12', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_12', 'ko-KR', '12위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', 'en-US', 'Rank Thirteen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', 'zh-TW', '第13名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', 'pt-BR', 'décimo terceiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', 'zh-CN', '第13名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', 'vi-VN', 'Hạng 13', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_13', 'ko-KR', '13위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', 'en-US', 'Rank Fourteen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', 'zh-TW', '第14名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', 'pt-BR', 'décimo quarto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', 'zh-CN', '第14名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', 'vi-VN', 'Hạng 14', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_14', 'ko-KR', '14위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', 'en-US', 'Rank Fifteen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', 'zh-TW', '第15名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', 'pt-BR', 'décimo quinto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', 'zh-CN', '第15名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', 'vi-VN', 'Hạng 15', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_15', 'ko-KR', '15위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', 'en-US', 'Rank Sixteen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', 'zh-TW', '第16名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', 'pt-BR', 'décimo sexto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', 'zh-CN', '第16名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', 'vi-VN', 'Hạng 16', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_16', 'ko-KR', '16위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', 'en-US', 'Rank Seventeen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', 'zh-TW', '第17名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', 'pt-BR', 'décimo sétimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', 'zh-CN', '第17名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', 'vi-VN', 'Hạng 17', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_17', 'ko-KR', '17위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', 'en-US', 'Rank Eighteen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', 'zh-TW', '第18名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', 'pt-BR', 'décimo oitavo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', 'zh-CN', '第18名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', 'vi-VN', 'Hạng 18', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_18', 'ko-KR', '18위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', 'en-US', 'Rank Nineteen', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', 'zh-TW', '第19名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', 'pt-BR', 'décimo nono lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', 'zh-CN', '第19名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', 'vi-VN', 'Hạng 19', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_19', 'ko-KR', '19위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', 'en-US', 'Rank Twenty', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', 'zh-TW', '第20名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', 'pt-BR', 'vigésimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', 'zh-CN', '第20名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', 'vi-VN', 'Hạng 20', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_20', 'ko-KR', '20위', now()),


       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', 'en-US', 'Rank Twenty-One', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', 'zh-TW', '第21名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', 'pt-BR', 'vigésimo primeiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', 'zh-CN', '第21名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', 'vi-VN', 'Hạng 21', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_21', 'ko-KR', '21위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', 'en-US', 'Rank Twenty-Two', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', 'zh-TW', '第22名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', 'pt-BR', 'vigésimo segundo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', 'zh-CN', '第22名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', 'vi-VN', 'Hạng 22', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_22', 'ko-KR', '22위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', 'en-US', 'Rank Twenty-Three', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', 'zh-TW', '第23名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', 'pt-BR', 'vigésimo terceiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', 'zh-CN', '第23名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', 'vi-VN', 'Hạng 23', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_23', 'ko-KR', '23위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', 'en-US', 'Rank Twenty-Four', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', 'zh-TW', '第24名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', 'pt-BR', 'vigésimo quarto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', 'zh-CN', '第24名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', 'vi-VN', 'Hạng 24', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_24', 'ko-KR', '24위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', 'en-US', 'Rank Twenty-Five', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', 'zh-TW', '第25名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', 'pt-BR', 'vigésimo quinto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', 'zh-CN', '第25名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', 'vi-VN', 'Hạng 25', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_25', 'ko-KR', '25위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', 'en-US', 'Rank Twenty-Six', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', 'zh-TW', '第26名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', 'pt-BR', 'vigésimo sexto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', 'zh-CN', '第26名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', 'vi-VN', 'Hạng 26', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_26', 'ko-KR', '26위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', 'en-US', 'Rank Twenty-Seven', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', 'zh-TW', '第27名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', 'pt-BR', 'vigésimo sétimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', 'zh-CN', '第27名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', 'vi-VN', 'Hạng 27', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_27', 'ko-KR', '27위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', 'en-US', 'Rank Twenty-Eight', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', 'zh-TW', '第28名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', 'pt-BR', 'vigésimo oitavo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', 'zh-CN', '第28名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', 'vi-VN', 'Hạng 28', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_28', 'ko-KR', '28위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', 'en-US', 'Rank Twenty-Nine', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', 'zh-TW', '第29名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', 'pt-BR', 'vigésimo nono lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', 'zh-CN', '第29名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', 'vi-VN', 'Hạng 29', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_29', 'ko-KR', '29위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', 'en-US', 'Rank Thirty', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', 'zh-TW', '第30名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', 'pt-BR', 'trigésimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', 'zh-CN', '第30名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', 'vi-VN', 'Hạng 30', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_30', 'ko-KR', '30위', now()),


       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', 'en-US', 'Rank Thirty-One', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', 'zh-TW', '第31名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', 'pt-BR', 'trigésimo primeiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', 'zh-CN', '第31名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', 'vi-VN', 'Hạng 31', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_31', 'ko-KR', '31위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', 'en-US', 'Rank Thirty-Two', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', 'zh-TW', '第32名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', 'pt-BR', 'trigésimo segundo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', 'zh-CN', '第32名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', 'vi-VN', 'Hạng 32', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_32', 'ko-KR', '32위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', 'en-US', 'Rank Thirty-Three', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', 'zh-TW', '第33名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', 'pt-BR', 'trigésimo terceiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', 'zh-CN', '第33名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', 'vi-VN', 'Hạng 33', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_33', 'ko-KR', '33위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', 'en-US', 'Rank Thirty-Four', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', 'zh-TW', '第34名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', 'pt-BR', 'trigésimo quarto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', 'zh-CN', '第34名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', 'vi-VN', 'Hạng 34', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_34', 'ko-KR', '34위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', 'en-US', 'Rank Thirty-Five', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', 'zh-TW', '第35名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', 'pt-BR', 'trigésimo quinto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', 'zh-CN', '第35名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', 'vi-VN', 'Hạng 35', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_35', 'ko-KR', '35위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', 'en-US', 'Rank Thirty-Six', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', 'zh-TW', '第36名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', 'pt-BR', 'trigésimo sexto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', 'zh-CN', '第36名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', 'vi-VN', 'Hạng 36', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_36', 'ko-KR', '36위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', 'en-US', 'Rank Thirty-Seven', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', 'zh-TW', '第37名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', 'pt-BR', 'trigésimo sétimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', 'zh-CN', '第37名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', 'vi-VN', 'Hạng 37', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_37', 'ko-KR', '37위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', 'en-US', 'Rank Thirty-Eight', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', 'zh-TW', '第38名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', 'pt-BR', 'trigésimo oitavo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', 'zh-CN', '第38名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', 'vi-VN', 'Hạng 38', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_38', 'ko-KR', '38위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', 'en-US', 'Rank Thirty-Nine', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', 'zh-TW', '第39名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', 'pt-BR', 'trigésimo nono lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', 'zh-CN', '第39名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', 'vi-VN', 'Hạng 39', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_39', 'ko-KR', '39위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', 'en-US', 'Rank Forty', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', 'zh-TW', '第40名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', 'pt-BR', 'quadragésimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', 'zh-CN', '第40名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', 'vi-VN', 'Hạng 40', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_40', 'ko-KR', '40위', now()),


       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', 'en-US', 'Rank Forty-One', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', 'zh-TW', '第41名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', 'pt-BR', 'quadragésimo primeiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', 'zh-CN', '第41名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', 'vi-VN', 'Hạng 41', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_41', 'ko-KR', '41위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', 'en-US', 'Rank Forty-Two', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', 'zh-TW', '第42名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', 'pt-BR', 'quadragésimo segundo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', 'zh-CN', '第42名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', 'vi-VN', 'Hạng 42', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_42', 'ko-KR', '42위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', 'en-US', 'Rank Forty-Three', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', 'zh-TW', '第43名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', 'pt-BR', 'quadragésimo terceiro lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', 'zh-CN', '第43名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', 'vi-VN', 'Hạng 43', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_43', 'ko-KR', '43위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', 'en-US', 'Rank Forty-Four', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', 'zh-TW', '第44名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', 'pt-BR', 'quadragésimo quarto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', 'zh-CN', '第44名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', 'vi-VN', 'Hạng 44', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_44', 'ko-KR', '44위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', 'en-US', 'Rank Forty-Five', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', 'zh-TW', '第45名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', 'pt-BR', 'quadragésimo quinto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', 'zh-CN', '第45名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', 'vi-VN', 'Hạng 45', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_45', 'ko-KR', '45위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', 'en-US', 'Rank Forty-Six', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', 'zh-TW', '第46名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', 'pt-BR', 'quadragésimo sexto lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', 'zh-CN', '第46名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', 'vi-VN', 'Hạng 46', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_46', 'ko-KR', '46위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', 'en-US', 'Rank Forty-Seven', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', 'zh-TW', '第47名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', 'pt-BR', 'quadragésimo sétimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', 'zh-CN', '第47名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', 'vi-VN', 'Hạng 47', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_47', 'ko-KR', '47위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', 'en-US', 'Rank Forty-Eight', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', 'zh-TW', '第48名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', 'pt-BR', 'quadragésimo oitavo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', 'zh-CN', '第48名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', 'vi-VN', 'Hạng 48', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_48', 'ko-KR', '48위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', 'en-US', 'Rank Forty-Nine', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', 'zh-TW', '第49名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', 'pt-BR', 'quadragésimo nono lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', 'zh-CN', '第49名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', 'vi-VN', 'Hạng 49', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_49', 'ko-KR', '49위', now()),

       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', 'en-US', 'Rank Fifty', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', 'zh-TW', '第50名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', 'pt-BR', 'quinquagésimo lugar', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', 'zh-CN', '第50名', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', 'vi-VN', 'Hạng 50', now()),
       ('BACK_END', 'LOOKUP_ACTIVITY_DAILY_RANKING_50', 'ko-KR', '50위', now());


UPDATE `i18n_message` SET message = 'thưởng', `updated_time` = '1750243517614' WHERE message_key = 'LOOKUP_11018' AND language = 'vi-VN';

