
INSERT INTO `system_param` ( `type`, `code`, `value`, `value_desc`, `description`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('venue_code', 'DG2', 'LOOKUP_VENUE_INIT_NAME_DG2', 'DG2真人', 'DG2真人', 1, NULL, '1', NULL);

INSERT INTO `i18n_message` ( `message_type`, `message_key`, `language`, `message`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('BACK_END', 'LOOKUP_VENUE_INIT_NAME_DG2', 'vi-VN', 'DG2 Trực tiếp', 1, 1741075204303, '1', NULL);
INSERT INTO `i18n_message` ( `message_type`, `message_key`, `language`, `message`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('BACK_END', 'LOOKUP_VENUE_INIT_NAME_DG2', 'zh-CN', 'DG2真人', 1, 1735274608799, '1', NULL);
INSERT INTO `i18n_message` ( `message_type`, `message_key`, `language`, `message`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('BACK_END', 'LOOKUP_VENUE_INIT_NAME_DG2', 'pt-BR', 'DG2 Cassino ao Vivo', 1, 1735274608799, '1', NULL);
INSERT INTO `i18n_message` ( `message_type`, `message_key`, `language`, `message`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('BACK_END', 'LOOKUP_VENUE_INIT_NAME_DG2', 'zh-TW', 'DG2 真人', 1, 1735274608799, '1', NULL);
INSERT INTO `i18n_message` ( `message_type`, `message_key`, `language`, `message`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('BACK_END', 'LOOKUP_VENUE_INIT_NAME_DG2', 'en-US', 'JDG2 Live Casino', 1, 1735274608799, '1', NULL);
INSERT INTO `i18n_message` ( `message_type`, `message_key`, `language`, `message`, `created_time`, `updated_time`, `creator`, `updater`) VALUES ('BACK_END', 'LOOKUP_VENUE_INIT_NAME_DG2', 'ko-KR', 'DG2 라이브 카지노', 1745826480664, 1745826480664, '1', '1');


INSERT INTO `venue_info` ( `venue_code`, `venue_currency_type`, `currency_code`, `venue_desc`, `sign_venue_name_i18n_code`, `venue_type`, `venue_join_type`, `venue_platform`, `venue_platform_name`, `venue_name`, `venue_icon`, `pc_venue_icon`, `h5_venue_icon`, `pc_background_code`, `pc_logo_code`, `icon_i18n_code`, `pc_icon_i18n_code`, `h5_icon_i18n_code`, `valid_proportion`, `venue_proportion`, `proportion_type`, `status`, `bet_url`, `api_url`, `game_url`, `merchant_no`, `aes_key`, `merchant_key`, `bet_key`, `creator_name`, `created_time`, `updater_name`, `updated_time`, `remark`, `maintenance_start_time`, `maintenance_end_time`, `name_prefix`, `creator`, `updater`) VALUES ( 'DG2', 2, 'MYR,KVND,PHP,USD,PKR,INR,KRW,VND,USDT', NULL, NULL, 2, 3, 'DG2', 'DG2', 'DG2真人', NULL, 'baowang/a06fc5d78a07498c8540788b03d799d3.png', 'baowang/2330a6a8eed44101ab095f84b658e524.png', NULL, NULL, NULL, 'BIZ_PC_VENUE_ICON_518161', 'BIZ_H5_VENUE_ICON_518162', 0.25, 2.00, 2, 1, 'https://api.dg99api.com/', 'https://api.dg99api.com/', 'https://api.dg99api.com/', 'DG01480206', '931562815e8d48bd8f99b2225b403110', '36908', NULL, NULL, 1756105583290, NULL, 1756105583290, '', NULL, NULL, NULL, 'alma01', 'alma01');
